### ISSUE TITLE
Add roslaunch test to all packages with launch files

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/ros_industrial_issues#11]
The roslaunch test ( http://wiki.ros.org/catkin/migrating_from_rosbuild#Test_Macros ) should be added to all packages that contain any launch files.  The test ensures that the package depencies capture the launch dependencies.

- [x] `industrial_core`: ros-industrial/industrial_core#179
- [x] `fanuc`: ros-industrial/fanuc#30
- [x] `abb`: no tracking issue (addressed in ros-industrial/abb#43)
- [x] `motoman`: ros-industrial/motoman#178
- [x] `universal_robot`: ros-industrial/universal_robot#314

**Comment by gavanderhoorn** [comment]
Status `motoman`: most (all?) support pkgs have roslaunch tests for the included launch files. No tests in the moveit config(s).

Status `universal_robot`: no roslaunch testing in any of the pkgs.

**Comment by ipa-nhg** [comment]
For motoman looks like it is already done.

For universal_robot: https://github.com/ros-industrial/universal_robot/pull/362

**Comment by gavanderhoorn** [comment]
Done with the merge of ros-industrial/universal_robot#362.
