### ISSUE TITLE
xacro run depend missing from all support packages?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#20]
Even though all support packages (and also the various `_config` pkgs) contain xacro's, none of them declare a (run) dependency on the `xacro` package itself.

As the `load_X.launch` launch files in the newer support packages load an xacro, I think the dependency should be added.

Affected packages:
- [x] ABB (ros-industrial/abb#22)
- [x] Fanuc (ros-industrial/fanuc#67)
- [x] Motoman (ros-industrial/motoman#177)
- [ ] Universal Robot (ros-industrial/universal_robot#313)

**Comment by gavanderhoorn** [comment]
Just checked all repos listed in the OP: `motoman` and `universal_robot` pkgs still haven't been fixed.

**Comment by gavanderhoorn** [comment]
ros-industrial/universal_robot#343 adds this to UR pkgs, so closing this as completed as merging that PR may/will take a while.

**Comment by gavanderhoorn** [comment]
Thanks @ipa-hsd for your contributions :+1:
